/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c1167315-da43-423c-9e16-e5cac3e9a664",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_MfDudGCqi",
    "aws_user_pools_web_client_id": "7335oun5doiqj75apmm495qqnf",
    "oauth": {}
};


export default awsmobile;
