/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:8df8e573-250f-4fe7-a195-3c99b90f22f6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_PBClv3d3J",
    "aws_user_pools_web_client_id": "2eaah8gqv99l29rnhgb81u6t41",
    "oauth": {}
};


export default awsmobile;
