/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:7d2c19f5-5a8f-4810-af70-418e086ba449",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_ug8Dndu40",
    "aws_user_pools_web_client_id": "4os6p8g00pdtkat2tno6luivdh",
    "oauth": {}
};


export default awsmobile;
